package sri.sysint.sri_starter_back.repository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import sri.sysint.sri_starter_back.model.ShiftMonthlyPlan;

public interface ShiftMonthlyPlanRepo extends JpaRepository<ShiftMonthlyPlan, BigDecimal>{
	@Query(value = "SELECT * FROM SRI_IMPP_D_DAILY_PLAN_CURING WHERE MO_ID = :moId AND DATE = :date", nativeQuery = true)
	List<ShiftMonthlyPlan> findByMoIdAndDate(@Param("moId") String moId, @Param("date") Date date);
	
	@Query(value = "SELECT COUNT(*) FROM SRI_IMPP_M_BUILDING", nativeQuery = true)
    BigDecimal getNewId();
	
	@Query(value = "SELECT * "
			+ "            FROM SRI_IMPP_D_DAILY_PLAN_CURING "
			+ "            WHERE ACTUAL_DATE = ("
			+ "                SELECT MAX(ACTUAL_DATE) "
			+ "                FROM SRI_IMPP_D_DAILY_PLAN_CURING "
			+ "                WHERE ACTUAL_DATE < TO_DATE(:inputDate, 'DD-MM-YYYY')) AND ITEM_CURING = :itemCuring", nativeQuery = true)
	List<ShiftMonthlyPlan> findYesterdaysShiftPlan(@Param("inputDate") String inputDate, @Param("itemCuring") String itemCuring);
	
	@Query(value = "SELECT DESCRIPTION FROM SRI_IMPP_M_PRODUCT WHERE PART_NUMBER = :partNum", nativeQuery = true)
	String findDescriptionByPartNum(@Param("partNum") BigDecimal partNum);

	@Query(value = "SELECT "
			+ "    TO_CHAR(DATE_WD, 'DD-MM-YYYY') AS DATE_WD, "
			+ "    --SHIFT1 HOUR "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT1_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) / 60.0, 3) "
			+ "        WHEN SHIFT1_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT1_TOTAL_TIME / 60.0, 3) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT1_HOUR, "
			+ "    --SHIFT2 HOUR "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT2_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) / 60.0, 3) "
			+ "        WHEN SHIFT2_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT2_TOTAL_TIME / 60.0, 3) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT2_HOUR, "
			+ "    --SHIFT3 HOUR "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) -- Waktu sebelum tengah malam "
			+ "                OR "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) -- Waktu setelah tengah malam "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT3_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        ( "
			+ "                            LEAST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(SHIFT3_END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') "
			+ "                                END "
			+ "                            ) "
			+ "                            - "
			+ "                            GREATEST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                TO_DATE(SHIFT3_START_TIME, 'HH24:MI') "
			+ "                            ) "
			+ "                        ) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) "
			+ "                            OR "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) / 60.0, 3) "
			+ "        WHEN SHIFT3_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT3_TOTAL_TIME / 60.0, 3) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT3_HOUR, "
			+ "    --SHIFT1 CAPICITY "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT1_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        WHEN SHIFT1_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT1_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        ELSE 0 "
			+ "    END AS SHIFT1_CAPACITY, "
			+ "    --SHIFT2 CAPICITY "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT2_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        WHEN SHIFT2_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT2_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        ELSE 0 "
			+ "    END AS SHIFT2_CAPACITY, "
			+ "    --SHIFT3 CAPICITY "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) -- Waktu sebelum tengah malam "
			+ "                OR "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) -- Waktu setelah tengah malam "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT3_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        ( "
			+ "                            LEAST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(SHIFT3_END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') "
			+ "                                END "
			+ "                            ) "
			+ "                            - "
			+ "                            GREATEST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                TO_DATE(SHIFT3_START_TIME, 'HH24:MI') "
			+ "                            ) "
			+ "                        ) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) "
			+ "                            OR "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        WHEN SHIFT3_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT3_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        ELSE 0 "
			+ "    END AS SHIFT3_CAPACITY, "
			+ "    --SHIFT1 HOUR CHANGE MOULD "
			+ "    CASE "
			+ "        WHEN SHIFT1_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) <= 0 "
			+ "        THEN 0 "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT1_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) / 60.0, 3) "
			+ "        WHEN SHIFT1_TOTAL_TIME >= 120 THEN "
			+ "            ROUND(SHIFT1_TOTAL_TIME / 60.0, 3) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT1_HOUR_CHANGE_MOULD, "
			+ "    --SHIFT2 HOUR CHANGE MOULD "
			+ "    CASE "
			+ "        WHEN SHIFT2_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) <= 0 "
			+ "        THEN 0 "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT2_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) / 60.0, 3) "
			+ "        WHEN SHIFT2_TOTAL_TIME >= 120 THEN "
			+ "            ROUND(SHIFT2_TOTAL_TIME / 60.0, 3) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT2_HOUR_CHANGE_MOULD, "
			+ "    --SHIFT3 HOUR CHANGE MOULD "
			+ "    CASE "
			+ "        WHEN SHIFT3_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT3_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT3_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) -- Waktu sebelum tengah malam "
			+ "                            OR "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) -- Waktu setelah tengah malam "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) <= 0 "
			+ "        THEN 0 "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) -- Waktu sebelum tengah malam "
			+ "                OR "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) -- Waktu setelah tengah malam "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT3_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        ( "
			+ "                            LEAST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(SHIFT3_END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') "
			+ "                                END "
			+ "                            ) "
			+ "                            - "
			+ "                            GREATEST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                TO_DATE(SHIFT3_START_TIME, 'HH24:MI') "
			+ "                            ) "
			+ "                        ) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) "
			+ "                            OR "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) / 60.0, 3) "
			+ "        WHEN SHIFT3_TOTAL_TIME >= 120 THEN "
			+ "            ROUND(SHIFT3_TOTAL_TIME / 60.0, 3) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT3_HOUR_CHANGE_MOULD, "
			+ "    --SHIFT1 CAPICITY CHANGE MOULD "
			+ "    CASE "
			+ "        WHEN SHIFT1_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) <= 0 "
			+ "        THEN 0 "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT1_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        WHEN SHIFT1_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT1_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        ELSE 0 "
			+ "    END AS SHIFT1_CAPACITY_CHANGE_MOULD, "
			+ "    --SHIFT2 CAPICITY CHANGE MOULD "
			+ "    CASE "
			+ "        WHEN SHIFT2_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) <= 0 "
			+ "        THEN 0 "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT2_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        WHEN SHIFT2_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT2_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        ELSE 0 "
			+ "    END AS SHIFT2_CAPACITY_CHANGE_MOULD, "
			+ "    --SHIFT3 CAPICITY CHANGE MOULD "
			+ "    CASE "
			+ "        WHEN SHIFT3_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        (LEAST( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT3_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                        - GREATEST( "
			+ "                            TO_DATE(START_TIME, 'HH24:MI'), "
			+ "                            TO_DATE(SHIFT3_START_TIME, 'HH24:MI') "
			+ "                        )) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) -- Waktu sebelum tengah malam "
			+ "                            OR "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) -- Waktu setelah tengah malam "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) <= 0 "
			+ "        THEN 0 "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) -- Waktu sebelum tengah malam "
			+ "                OR "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) -- Waktu setelah tengah malam "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT3_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        ( "
			+ "                            LEAST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(SHIFT3_END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') "
			+ "                                END "
			+ "                            ) "
			+ "                            - "
			+ "                            GREATEST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                TO_DATE(SHIFT3_START_TIME, 'HH24:MI') "
			+ "                            ) "
			+ "                        ) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) "
			+ "                            OR "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        WHEN SHIFT3_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT3_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        ELSE 0 "
			+ "    END AS SHIFT3_CAPACITY_CHANGE_MOULD "
			+ "FROM "
			+ "    SRI_IMPP_D_WD_HOURS_SPECIFIC "
			+ "WHERE "
			+ "    DATE_WD BETWEEN TO_DATE('01-' || :month || '-' || :year, 'DD-MM-YYYY') "
			+ "    AND LAST_DAY(TO_DATE('01-' || :month || '-' || :year, 'DD-MM-YYYY')) "
			+ "    AND ( "
			+ "        DESCRIPTION = 'WD_NORMAL' "
			+ "        OR ( "
			+ "            (:itemCuring LIKE 'CN-%' AND DESCRIPTION = 'OT_TL') "
			+ "            OR (:itemCuring LIKE 'CM-%' AND DESCRIPTION = 'OT_TT') "
			+ "        ) "
			+ "    ) "
			+ "    AND (SHIFT1_TOTAL_TIME > 0 OR SHIFT2_TOTAL_TIME > 0 OR SHIFT3_TOTAL_TIME > 0)",  nativeQuery = true)
	List<Map<String, Object>> getCuringCapacity(@Param("itemCuring") String itemCuring, @Param("operationShortText") String operationShortText, @Param("cavity") int cavity, @Param("month") int month, @Param("year") int year);
	
	@Query(value = "SELECT "
			+ "    TO_CHAR(DATE_WD, 'DD-MM-YYYY') AS DATE_WD, "
			+ "    --SHIFT1 HOUR "
			+ "    CASE "
			+ "        WHEN DATE_WD = ( "
			+ "            SELECT MIN(DATE_WD) "
			+ "            FROM SRI_IMPP_D_WD_HOURS_SPECIFIC "
			+ "            WHERE "
			+ "                DATE_WD BETWEEN TO_DATE('01-' || :month || '-' || :year, 'DD-MM-YYYY') "
			+ "                AND LAST_DAY(TO_DATE('01-' || :month || '-' || :year, 'DD-MM-YYYY')) "
			+ "                AND (SHIFT1_TOTAL_TIME > 0 OR SHIFT2_TOTAL_TIME > 0 OR SHIFT3_TOTAL_TIME > 0) "
			+ "        ) THEN "
			+ "            CASE "
			+ "                WHEN EXISTS ( "
			+ "                    SELECT 1 "
			+ "                    FROM SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "                    AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                    AND ( "
			+ "                        TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                        AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                    ) "
			+ "                ) THEN GREATEST( "
			+ "                    ROUND( "
			+ "                        ((SHIFT1_TOTAL_TIME - 120) - ( "
			+ "                            SELECT "
			+ "                                (LEAST(TO_DATE(END_TIME, 'HH24:MI'), TO_DATE(SHIFT1_END_TIME, 'HH24:MI')) - GREATEST(TO_DATE(START_TIME, 'HH24:MI'), TO_DATE(SHIFT1_START_TIME, 'HH24:MI'))) * 24 * 60 "
			+ "                            FROM "
			+ "                                SRI_IMPP_M_STOP_MACHINE "
			+ "                            WHERE "
			+ "                                WORK_CENTER_TEXT = :operationShortText "
			+ "                                AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                                AND ( "
			+ "                                    TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                                    AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                                ) "
			+ "                            AND ROWNUM = 1 "
			+ "                        )) / 60.0, 3), 0) "
			+ "                ELSE GREATEST(ROUND((SHIFT1_TOTAL_TIME - 120) / 60.0, 3), 0) "
			+ "            END "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN GREATEST( "
			+ "            ROUND( "
			+ "                (SHIFT1_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        (LEAST(TO_DATE(END_TIME, 'HH24:MI'), TO_DATE(SHIFT1_END_TIME, 'HH24:MI')) - GREATEST(TO_DATE(START_TIME, 'HH24:MI'), TO_DATE(SHIFT1_START_TIME, 'HH24:MI'))) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                )) / 60.0, 3), 0) "
			+ "        WHEN SHIFT1_TOTAL_TIME != 0 THEN GREATEST(ROUND(SHIFT1_TOTAL_TIME / 60.0, 3), 0) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT1_HOUR, "
			+ "    --SHIFT2 HOUR "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT2_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        (LEAST(TO_DATE(END_TIME, 'HH24:MI'), TO_DATE(SHIFT2_END_TIME, 'HH24:MI')) - GREATEST(TO_DATE(START_TIME, 'HH24:MI'), TO_DATE(SHIFT2_START_TIME, 'HH24:MI'))) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) / 60.0, 3) "
			+ "        WHEN SHIFT2_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT2_TOTAL_TIME / 60.0, 3) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT2_HOUR, "
			+ "    --SHIFT3 HOUR "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) -- Waktu sebelum tengah malam "
			+ "                OR "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) -- Waktu setelah tengah malam "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT3_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        ( "
			+ "                            LEAST(CASE "
			+ "                                    WHEN TO_DATE(END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(SHIFT3_END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') "
			+ "                                END "
			+ "                            ) "
			+ "                            - "
			+ "                            GREATEST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                TO_DATE(SHIFT3_START_TIME, 'HH24:MI') "
			+ "                            ) "
			+ "                        ) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) "
			+ "                            OR "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) / 60.0, 3) "
			+ "        WHEN SHIFT3_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT3_TOTAL_TIME / 60.0, 3) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT3_HOUR, "
			+ "    --SHIFT1 CAPACITY "
			+ "    CASE "
			+ "        WHEN DATE_WD = ( "
			+ "            SELECT MIN(DATE_WD) "
			+ "            FROM SRI_IMPP_D_WD_HOURS_SPECIFIC "
			+ "            WHERE "
			+ "                DATE_WD BETWEEN TO_DATE('01-' || :month || '-' || :year, 'DD-MM-YYYY') "
			+ "                AND LAST_DAY(TO_DATE('01-' || :month || '-' || :year, 'DD-MM-YYYY')) "
			+ "                AND (SHIFT1_TOTAL_TIME > 0 OR SHIFT2_TOTAL_TIME > 0 OR SHIFT3_TOTAL_TIME > 0) "
			+ "        ) THEN "
			+ "            CASE "
			+ "                WHEN EXISTS ( "
			+ "                    SELECT 1 "
			+ "                    FROM SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "                    AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                    AND ( "
			+ "                        TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                        AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                    ) "
			+ "                ) THEN GREATEST( "
			+ "                    ROUND( "
			+ "                        ((SHIFT1_TOTAL_TIME - 120) - ( "
			+ "                            SELECT "
			+ "                                (LEAST(TO_DATE(END_TIME, 'HH24:MI'), TO_DATE(SHIFT1_END_TIME, 'HH24:MI')) - GREATEST(TO_DATE(START_TIME, 'HH24:MI'), TO_DATE(SHIFT1_START_TIME, 'HH24:MI'))) * 24 * 60 "
			+ "                            FROM "
			+ "                                SRI_IMPP_M_STOP_MACHINE "
			+ "                            WHERE "
			+ "                                WORK_CENTER_TEXT = :operationShortText "
			+ "                                AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                                AND ( "
			+ "                                    TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                                    AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                                ) "
			+ "                            AND ROWNUM = 1 "
			+ "                        )) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity, 0) "
			+ "                ELSE GREATEST(ROUND((SHIFT1_TOTAL_TIME - 120) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity, 0) "
			+ "            END "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN GREATEST( "
			+ "            ROUND( "
			+ "                (SHIFT1_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        (LEAST(TO_DATE(END_TIME, 'HH24:MI'), TO_DATE(SHIFT1_END_TIME, 'HH24:MI')) - GREATEST(TO_DATE(START_TIME, 'HH24:MI'), TO_DATE(SHIFT1_START_TIME, 'HH24:MI'))) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT1_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT1_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                )) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity, 0) "
			+ "        WHEN SHIFT1_TOTAL_TIME != 0 THEN GREATEST(ROUND(SHIFT1_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity, 0) "
			+ "        ELSE 0 "
			+ "    END AS SHIFT1_CAPACITY, "
			+ "    --SHIFT2 CAPICITY "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT2_TOTAL_TIME - ( "
			+ "                    SELECT "
			+ "                        (LEAST(TO_DATE(END_TIME, 'HH24:MI'), TO_DATE(SHIFT2_END_TIME, 'HH24:MI')) - GREATEST(TO_DATE(START_TIME, 'HH24:MI'), TO_DATE(SHIFT2_START_TIME, 'HH24:MI'))) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT2_START_TIME, 'HH24:MI') "
			+ "                            AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT2_END_TIME, 'HH24:MI') "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        WHEN SHIFT2_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT2_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        ELSE 0 "
			+ "    END AS SHIFT2_CAPACITY, "
			+ "    --SHIFT3 CAPICITY "
			+ "    CASE "
			+ "        WHEN EXISTS ( "
			+ "            SELECT 1 "
			+ "            FROM SRI_IMPP_M_STOP_MACHINE "
			+ "            WHERE WORK_CENTER_TEXT = :operationShortText "
			+ "            AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "            AND ( "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) -- Waktu sebelum tengah malam "
			+ "                OR "
			+ "                (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) -- Waktu setelah tengah malam "
			+ "            ) "
			+ "        ) THEN "
			+ "            ROUND(( "
			+ "                SHIFT3_TOTAL_TIME - 120 - ( "
			+ "                    SELECT "
			+ "                        ( "
			+ "                            LEAST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(END_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(SHIFT3_END_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(SHIFT3_END_TIME, 'HH24:MI') "
			+ "                                END "
			+ "                            ) "
			+ "                            - "
			+ "                            GREATEST( "
			+ "                                CASE "
			+ "                                    WHEN TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_START_TIME, 'HH24:MI') THEN "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') + 1 "
			+ "                                    ELSE "
			+ "                                        TO_DATE(START_TIME, 'HH24:MI') "
			+ "                                END, "
			+ "                                TO_DATE(SHIFT3_START_TIME, 'HH24:MI') "
			+ "                            ) "
			+ "                        ) * 24 * 60 "
			+ "                    FROM "
			+ "                        SRI_IMPP_M_STOP_MACHINE "
			+ "                    WHERE "
			+ "                        WORK_CENTER_TEXT = :operationShortText "
			+ "                        AND TO_CHAR(DATE_PM, 'DD-MM-YYYY') = TO_CHAR(DATE_WD, 'DD-MM-YYYY') "
			+ "                        AND ( "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') > TO_DATE(SHIFT3_START_TIME, 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') <= TO_DATE('23:59', 'HH24:MI')) "
			+ "                            OR "
			+ "                            (TO_DATE(END_TIME, 'HH24:MI') >= TO_DATE('00:00', 'HH24:MI') AND TO_DATE(START_TIME, 'HH24:MI') < TO_DATE(SHIFT3_END_TIME, 'HH24:MI')) "
			+ "                        ) "
			+ "                    AND ROWNUM = 1 "
			+ "                ) "
			+ "            ) * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        WHEN SHIFT3_TOTAL_TIME != 0 THEN "
			+ "            ROUND(SHIFT3_TOTAL_TIME * 60 / (SELECT CT_SEC1 FROM SRI_IMPP_M_CT_CURING WHERE WIP = :itemCuring AND OPERATION_SHORT_TEXT = :operationShortText)) * :cavity "
			+ "        ELSE 0 "
			+ "    END AS SHIFT3_CAPACITY "
			+ "FROM "
			+ "    SRI_IMPP_D_WD_HOURS_SPECIFIC "
			+ "WHERE "
			+ "    DATE_WD BETWEEN TO_DATE('01-' || :month || '-' || :year, 'DD-MM-YYYY') "
			+ "    AND LAST_DAY(TO_DATE('01-' || :month || '-' || :year, 'DD-MM-YYYY')) "
			+ "    AND ( "
			+ "        DESCRIPTION = 'WD_NORMAL' "
			+ "        OR ( "
			+ "            (:itemCuring LIKE 'CN-%' AND DESCRIPTION = 'OT_TL') "
			+ "            OR (:itemCuring LIKE 'CM-%' AND DESCRIPTION = 'OT_TT') "
			+ "        ) "
			+ "    ) "
			+ "    AND (SHIFT1_TOTAL_TIME > 0 OR SHIFT2_TOTAL_TIME > 0 OR SHIFT3_TOTAL_TIME > 0)",  nativeQuery = true)
	List<Map<String, Object>> getCuringCapacityChangeMouldFirstDate(@Param("itemCuring") String itemCuring, @Param("operationShortText") String operationShortText, @Param("cavity") int cavity, @Param("month") int month, @Param("year") int year);
}
